- .gitignore
- pytest.ini
- src/utils/helpers.py
- tests/conftest.py
- tests/test_TravelProduct.py
1. conftest 작성 : login_driver 추가
(앱 실행 -> 로그인 -> 앱 종료)
2. helpers 공용 기능 추가 : 로그 저장 설정
: 스크린샷 저장 설정
: 요소 존재 확인
: 요소 클릭
: 자동 로그인
> [ADD] conftest 및 helpers 작성

- src/pages/BasePage.py
- src/utils/helpers.py
- tests/conftest.py
- 기존 helpers.py 내 Helpers 클래스 제거
- BasePage 상속 구조를 제거하고 login(driver, id, pw) 함수 단독 정의
- driver를 login 함수에 명시적으로 전달하는 방식 유지
- login_driver fixture에서 login 함수 호출 방식 반영
- Util 파일은 기능만 제공하고 검증/로깅은 각 테스트에서 담당하는 방향으로 구조 단순화
> [REFACTORING] helpers.py 구조 개선 및 login 유틸 함수 단독 정의

- src/pages/BasePage.py
- src/utils/helpers.py
1. BasePage
- send_keys 함수 추가
2. helpers
- 알림 허용 팝업 선택 위치 로그인 클릭 후로 변경
> [UPDATE] BasePage, helpers 코드 수정

- src/pages/BasePage.py
－요소 찾기/클릭 성공/실패 시, 어떤 locator가 대상인지 로그 출력 추가
－기능 함수 실패 시 스크린샷 파일명에 기능 함수 이름 및 _fail 붙이도록 수정
> [UPDATE] BasePage 요소 메서드 로깅 및 스크린샷 파일명 개선

- src/pages/MyPage.py
- src/utils/locators/MyPageLocator.py
- tests/test_MyPage.py
- BasePage.py 상속 코드 추가
- TC 1개 추가
- 마이페이지 테스트에 필요한 일부 로케이터 변수 코드 추가
> [UPDATE] MyPage.py / test_MyPage.py / MyPageLocator.py

- src/pages/TravelProduct.py
- src/utils/locators/TravelProductLocator.py
- tests/test_TravelProduct.py
대상 파일: page, Locator, test
- 여행 패키지 페이지 진입 확인 테스트 함수 추가
- 여행 패키지 페이지 UI요소 노출 확인 테스트 함수 추가
- 여행 패키지 페이지 검색 확인 - 검색 결과 존재하는 케이스 테스트 함수 추가
- 여행 패키지 페이지 검색 확인 - 검색 결과 존재하지 않는 케이스 테스트 함수 추가
- 여행 패키지 페이지 전체 필터 확인 함수 추가(수정 예정)
- 여행 패키지 페이지 필터 확인 (수정 예정) : parametrize 사용하여 10개 테스트 커버
> [ADD] TravelProduct 관련 코드 추가

- src/pages/Home.py
- src/utils/locators/HomeLocator.py
- tests/test_Home.py
- HomeLocator: XPath → ACCESSIBILITY_ID로 일부 요소 변경 (content-desc 활용)
- 홈 탭 관련 TC 일부 추가
- 인기 관광지 혼잡도 영역 진입 시 "데이터를 불러오는데 실패했습니다" 발생 → 해당 TC 임시 보류
> [UPDATE] HomeLocator 일부 ACCESSIBILITY_ID로 수정 및 TC 추가

- src/pages/Chatting.py
- src/resources/testdata/test_data.py
- src/utils/locators/ChattingLocator.py
- tests/test_Chatting.py
class TestTP03에서 send_keys 함수가 안돼서 자꾸 오류 뜸... 내일 다시 시도해봐야할듯...
우선 여기서 마무리!
> [UPDATE] testdata 폴더에 test_data.py 추가, 로케이터, 테스트코드, 함수 추가 작성

- src/pages/BasePage.py
- src/pages/Register.py
- src/utils/locators/RegisterLocator.py
- tests/test_Register.py
- get_attribute 함수 추가
- handle_exception 함수를 추가하면서, 예외 사항 반복 코드 개선
- hide_keyboard 함수를 추가하면서, 키보드로 DOM 가리는 현상 수정
- TC 14개 작성
- LR03 클래스 내 하드코딩된 테스트 데이터를 resource/testdata 에 옮길 예정
> [UPDATE] BasePage, Register, test_Register 추가

- src/pages/TravelProduct.py
- tests/test_TravelProduct.py
- 패키지 정보 저장 함수 스크롤 업 포함된 기능 별도로 나눔
- save_all_packages, save_all_packages_back_top
- return_scroll_count=False 추가하여 선택적 호출 방식으로 변경
- BasePage get_attribute 함수 적용
- 찜 선택 함수에 time 추가하여 찜 선택 후 적용 대기 추가
- 변경된 TravelProduct  적용
> [UPDATE] TravelProduct 수정

- pytest.ini
- wip: 작업 중인 테스트
- blocked: 외부 요인으로 개발/실행 보류된 테스트
- done: 개발 및 테스트 완료
> [ADD] pytest.ini에 mark 추가

- src/pages/Home.py
- src/utils/locators/HomeLocator.py
- tests/test_Home.py
1. 홈 페이지 함수 추가
- 날씨 위젯 로딩 완료까지 대기 함수
- 여행갤러리 글 정보 추출 함수
- 여행갤러리 글 좋아요 수 추출 함수
- 요소가 사라질때까지 대기 함수
2. 로케이터
- TXT -> TITLE로 변경
- 지역탐방 페이지 요소 추가
- 여행갤러리 페이지 요소 추가
- 지역탐방/여행갤러리 주요 UI 요소 리스트 추가
3. TC
- mark 추가
- 테스트 함수 추가
> [ADD] 홈 페이지 함수, 로케이터, tc코드 추가

- .gitignore
- src/pages/Chatting.py
- src/utils/locators/ChattingLocator.py
- tests/test_Chatting.py
스와이프 함수 작성하려했으나 from appium.webdriver.common.pointer_input import PointerInput 가 임포트가 안됨... 우선 제외하고 진행하기로 함. 
send_keys도 계속 안돼서 해결 방법 찾는중...
> [UPDATE] 로케이터 수정, 함수 추가작성, 테스트 코드 추가작성

- src/pages/TravelProduct.py
- src/utils/locators/TravelProductLocator.py
- tests/test_TravelProduct.py
- 주석 정리
- 상세화면 테스트 관련 코드 추가
- 공용 로케이터 클래스 생성
- 기존 로케이터 공용 로케이터 사용하는 방식으로 수정(복잡한 XPATH 제외)
- 상세화면 테스트 코드 추가
1. 상세 화면 진입
2. 상세 화면 UI 요소 확인
3. 가이드 채팅 진입
4. 여행 코스 장소 선택
- 테스트 확인된 건 mark.done 추가
> [UPDATE] TravelProduct

- src/pages/MyPage.py
- src/utils/locators/MyPageLocator.py
- tests/test_MyPage.py
- 메서드 신규 추가
- 로그인 후 닉네임 값 받아오기
- 마이페이지 탭 진입
- 프로필 페이지 진입
- 'Locator' 단어가 포함된 Class명에서 해당 단어 삭제
- 변수명 간소화
- 신규 필요 로케이터 값 추가
- 기 작성 TC 내용 수정
- 신규 테스트 클래스 및 함수 추가
- TC 내용 주석으로 Precondition / Steps / Expected Result 구분
> [UPDATE] MyPage.py / MyPageLocator.py / MyPage.py

- tests/test_Home.py
- 관광지 혼잡도 데이터 로딩 오류 해결로 tc 구현 완료
> [ADD] 홈 tc코드 추가

- src/pages/BasePage.py
- src/pages/Chatting.py
- src/utils/locators/ChattingLocator.py
- tests/test_Chatting.py
> [UPDATE] basepage 함수 추가, 테스트 코드 작성

- src/utils/locators/MyPageLocator.py
- tests/test_MyPage.py
- 프로필 페이지 > 이메일 표시 영역 로케이터 생성 함수 추가
- 신규 TC 추가
- MP04 : 스크린샷 검증 코드 삽입 필요
- MP05 : 완료
> [UPDATE] MyPageLocator.py / test_MyPage.py

- tests/test_Home.py
- 하드코딩되고 반복되는 테스트 데이터를 별도 .py 파일로 분리하여 재사용성과 유지보수성 향상
- 현재 오류 방지를 위해 .gitignore에 testdata/가 추가되어 있으며, 모든 팀원의 데이터 분리가 완료되면 해당 항목 제거 예정
> [ADD] 홈 테스트 데이터 파일 분리

- Dockerfile
- Jenkinsfile
- docker-compose.yaml
- requirements.txt
- dockerfile 제작
- docker-compose.yaml 제작
- Jenkinsfile 수정
- requirements.txt 수정
> [ADD] Jenkins 연동
